### ISSUE TITLE
Social networks examples are broken

### ISSUE THREAD

**Issue by gsomix** [evelinag/evelinag.github.io#1]
Hello. It seems examples are broken by merge conflict.

- http://evelinag.com/blog/2015/12-15-star-wars-social-network/interactions.html
- http://evelinag.com/blog/2016/01-25-social-network-force-awakens/interactions.html

**Comment by evelinag** [comment]
Fixed now, sorry for the delay!

**Comment by gsomix** [comment]
Thanks!
